'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {boundarySegments,intersections}=require('../track-boundaries');
const {readPitMesh,section,spatialIndex}=require('../pit-surface');
const {surfaceBelow,transition}=require('../pit-triggers');
const left={segments:[[[0,4,0],[10,4,0]]]},right={segments:[[[0,-3,0],[10,-3,0]]]};
assert.equal(intersections([5,0,0],[1,0,0],left)[0].signedLeftM,4);
assert.equal(intersections([5,0,0],[1,0,0],right)[0].signedLeftM,-3);
assert.equal(intersections([5,0,0],[-1,0,0],left)[0].signedLeftM,-4);
assert.equal(intersections([5,0,5],[1,0,0],left).length,0);
assert.equal(intersections([20,0,0],[1,0,0],left).length,0);
assert.equal(intersections([5,0,0],[1,0,0],{segments:[...left.segments,...right.segments]}).length,2);
assert.throws(()=>intersections([0,0,0],[0,0,1],left),/tangent/);
assert.deepEqual(boundarySegments([[0,2,3,0],[10,2,3,1]],-1).segments[0][0],[0,-3,2]);
const obj='o 1_pitlane_0\nv 0 -200 0\nv 1000 -200 0\nv 1000 300 0\nv 0 300 0\nf 1 2 3\nf 1 3 4';
const mesh=readPitMesh(obj),slice=section([5,0,.3],[1,0,0],mesh.triangles);
assert.equal(mesh.triangles.length,2);assert(Math.abs(slice.containing.min+2)<1e-8);assert(Math.abs(slice.containing.max-3)<1e-8);
assert.equal(section([15,0,0],[1,0,0],mesh.triangles).containing,null);
assert.equal(section([5,0,10],[1,0,0],mesh.triangles).containing,null);
assert(surfaceBelow([5,0,.3],mesh.triangles));assert.equal(surfaceBelow([5,0,10],mesh.triangles),null);
const crossing=transition([-2,0,.3],[2,0,.3],p=>Boolean(surfaceBelow(p,mesh.triangles)));
assert.equal(crossing.type,'entry');assert(Math.abs(crossing.positionM[0])<1e-6);
assert.throws(()=>transition([2,0,.3],[3,0,.3],p=>Boolean(surfaceBelow(p,mesh.triangles))),/bracket/);
assert.deepEqual(section([5,0,.3],[1,0,0],spatialIndex(mesh.triangles).query([5,0,.3])),slice);
assert.throws(()=>readPitMesh(obj.replace('f 1 2 3','f 1 2 99')),/triangle/);
const result=JSON.parse(fs.readFileSync(path.join(__dirname,'../research/kalinago-boundaries02.json')));
assert.equal(result.installable,false);assert.equal(result.edges.length,648);assert.equal(result.issues.length,0);
const correct=result.axisComparisons.find(a=>a.csvZSign===-1),incorrect=result.axisComparisons.find(a=>a.csvZSign===1);
assert.equal(correct.totalExpected,7224);assert.equal(correct.missing,0);assert(incorrect.missing>6000);
assert(correct.sides.side_l.widthErrorM.p95<.06);assert(correct.sides.side_r.widthErrorM.p95<.05);
assert(result.edges.every(e=>e.sourceLeft.signedLeftM<0&&e.sourceRight.signedLeftM>0));
const pit=JSON.parse(fs.readFileSync(path.join(__dirname,'../research/kalinago-pit-surfaces01.json')));
assert.equal(pit.sections.length,579);assert.equal(pit.missing.length,327);
assert(pit.sections.slice(146,398).every(s=>s.containing));
const allRoads=JSON.parse(fs.readFileSync(path.join(__dirname,'../research/kalinago-pit-surfaces02.json')));
assert.equal(allRoads.missing.length,0);assert.equal(allRoads.sections.length,579);
assert(allRoads.sections.every(s=>s.containing.min<=.01&&s.containing.max>=-.01&&s.containing.max>s.containing.min));
assert.equal(allRoads.installable,false);
console.log('Boundary geometry, axis rejection evidence and real pit coverage checks passed');
