#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AITeamEmails

#include "Basic.hpp"

#include "AITeamEmails_classes.hpp"
#include "AITeamEmails_parameters.hpp"


SDK_NAMESPACE_START

// Function AITeamEmails.AITeamEmails_C.CarDevSection
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailTeamData&            TeamData                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FNarrativeStaffMember&     PrincipalData                                          (BlueprintVisible, BlueprintReadOnly, Parm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FEmailSection*                   CarDevSection_0                                        (Parm, OutParm)

void UAITeamEmails_C::CarDevSection(const struct FEmailTeamData& TeamData, const struct FNarrativeStaffMember& PrincipalData, class UObject* __WorldContext, struct FEmailSection* CarDevSection_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "CarDevSection");

	Params::AITeamEmails_C_CarDevSection Parms{};

	Parms.TeamData = std::move(TeamData);
	Parms.PrincipalData = std::move(PrincipalData);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (CarDevSection_0 != nullptr)
		*CarDevSection_0 = std::move(Parms.CarDevSection_0);
}


// Function AITeamEmails.AITeamEmails_C.ChampionshipResults
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailData&                EmailData                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   SimDay                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::ChampionshipResults(const struct FEmailData& EmailData, int32 SimDay, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "ChampionshipResults");

	Params::AITeamEmails_C_ChampionshipResults Parms{};

	Parms.EmailData = std::move(EmailData);
	Parms.SimDay = SimDay;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function AITeamEmails.AITeamEmails_C.CompetitorDriverSigned
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::CompetitorDriverSigned(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "CompetitorDriverSigned");

	Params::AITeamEmails_C_CompetitorDriverSigned Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function AITeamEmails.AITeamEmails_C.CreateDriverAttachmentFromStandings
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailFormulaStandingData& DriverStandingsData                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// TArray<struct FEmailAttachmentStat>&    EmailAttachment                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::CreateDriverAttachmentFromStandings(const struct FEmailFormulaStandingData& DriverStandingsData, TArray<struct FEmailAttachmentStat>& EmailAttachment, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "CreateDriverAttachmentFromStandings");

	Params::AITeamEmails_C_CreateDriverAttachmentFromStandings Parms{};

	Parms.DriverStandingsData = std::move(DriverStandingsData);
	Parms.EmailAttachment = std::move(EmailAttachment);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	EmailAttachment = std::move(Parms.EmailAttachment);
}


// Function AITeamEmails.AITeamEmails_C.CreateTeamAttachment
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailFormulaStandingData& EmailFormulaStandingData                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// TArray<struct FEmailAttachmentStat>&    TeamAttachment                                         (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::CreateTeamAttachment(const struct FEmailFormulaStandingData& EmailFormulaStandingData, TArray<struct FEmailAttachmentStat>& TeamAttachment, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "CreateTeamAttachment");

	Params::AITeamEmails_C_CreateTeamAttachment Parms{};

	Parms.EmailFormulaStandingData = std::move(EmailFormulaStandingData);
	Parms.TeamAttachment = std::move(TeamAttachment);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	TeamAttachment = std::move(Parms.TeamAttachment);
}


// Function AITeamEmails.AITeamEmails_C.FacilitySection
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailTeamData&            TeamData                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FNarrativeStaffMember&     PrincipalData                                          (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   TodaysDate                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FEmailSection*                   FactilitySection                                       (Parm, OutParm)
// int32*                                  ChosenBuildingString                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::FacilitySection(const struct FEmailTeamData& TeamData, const struct FNarrativeStaffMember& PrincipalData, int32 TodaysDate, class UObject* __WorldContext, struct FEmailSection* FactilitySection, int32* ChosenBuildingString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "FacilitySection");

	Params::AITeamEmails_C_FacilitySection Parms{};

	Parms.TeamData = std::move(TeamData);
	Parms.PrincipalData = std::move(PrincipalData);
	Parms.TodaysDate = TodaysDate;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (FactilitySection != nullptr)
		*FactilitySection = std::move(Parms.FactilitySection);

	if (ChosenBuildingString != nullptr)
		*ChosenBuildingString = Parms.ChosenBuildingString;
}


// Function AITeamEmails.AITeamEmails_C.GetDriverChampionshipsNames
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FEmailFormulaData&         FormulaData                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FString*                          OnestName                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
// class FString*                          TwondName                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
// class FString*                          ThreerdName                                            (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
// struct FLocStringParameter*             OnestGender                                            (Parm, OutParm)
// struct FLocStringParameter*             TwondGender                                            (Parm, OutParm)
// struct FLocStringParameter*             ThreerdGender                                          (Parm, OutParm)

void UAITeamEmails_C::GetDriverChampionshipsNames(const struct FEmailFormulaData& FormulaData, class UObject* __WorldContext, class FString* OnestName, class FString* TwondName, class FString* ThreerdName, struct FLocStringParameter* OnestGender, struct FLocStringParameter* TwondGender, struct FLocStringParameter* ThreerdGender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "GetDriverChampionshipsNames");

	Params::AITeamEmails_C_GetDriverChampionshipsNames Parms{};

	Parms.FormulaData = std::move(FormulaData);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (OnestName != nullptr)
		*OnestName = std::move(Parms.OnestName);

	if (TwondName != nullptr)
		*TwondName = std::move(Parms.TwondName);

	if (ThreerdName != nullptr)
		*ThreerdName = std::move(Parms.ThreerdName);

	if (OnestGender != nullptr)
		*OnestGender = std::move(Parms.OnestGender);

	if (TwondGender != nullptr)
		*TwondGender = std::move(Parms.TwondGender);

	if (ThreerdGender != nullptr)
		*ThreerdGender = std::move(Parms.ThreerdGender);
}


// Function AITeamEmails.AITeamEmails_C.GetDriverChampionshipWinners
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FEmailFormulaData&         EmailFormulaData                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int64*                                  ThisYearsWinner                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64*                                  LastYearsWinner                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::GetDriverChampionshipWinners(const struct FEmailFormulaData& EmailFormulaData, class UObject* __WorldContext, int64* ThisYearsWinner, int64* LastYearsWinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "GetDriverChampionshipWinners");

	Params::AITeamEmails_C_GetDriverChampionshipWinners Parms{};

	Parms.EmailFormulaData = std::move(EmailFormulaData);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (ThisYearsWinner != nullptr)
		*ThisYearsWinner = Parms.ThisYearsWinner;

	if (LastYearsWinner != nullptr)
		*LastYearsWinner = Parms.LastYearsWinner;
}


// Function AITeamEmails.AITeamEmails_C.GetPointsOfDriver
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FEmailFormulaData&         FormulaData                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   Driver                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  Points                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::GetPointsOfDriver(const struct FEmailFormulaData& FormulaData, int32 Driver, class UObject* __WorldContext, int32* Points)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "GetPointsOfDriver");

	Params::AITeamEmails_C_GetPointsOfDriver Parms{};

	Parms.FormulaData = std::move(FormulaData);
	Parms.Driver = Driver;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Points != nullptr)
		*Points = Parms.Points;
}


// Function AITeamEmails.AITeamEmails_C.GetStringFromPartRank
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PartRanking                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  PartRank                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::GetStringFromPartRank(int32 PartRanking, class UObject* __WorldContext, int32* PartRank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "GetStringFromPartRank");

	Params::AITeamEmails_C_GetStringFromPartRank Parms{};

	Parms.PartRanking = PartRanking;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (PartRank != nullptr)
		*PartRank = Parms.PartRank;
}


// Function AITeamEmails.AITeamEmails_C.GetStringFromRecentBuildings
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FEmailBuildingData>&      RecentBuildingsArray                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  BuildingStringNumber                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::GetStringFromRecentBuildings(TArray<struct FEmailBuildingData>& RecentBuildingsArray, class UObject* __WorldContext, int32* BuildingStringNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "GetStringFromRecentBuildings");

	Params::AITeamEmails_C_GetStringFromRecentBuildings Parms{};

	Parms.RecentBuildingsArray = std::move(RecentBuildingsArray);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	RecentBuildingsArray = std::move(Parms.RecentBuildingsArray);

	if (BuildingStringNumber != nullptr)
		*BuildingStringNumber = Parms.BuildingStringNumber;
}


// Function AITeamEmails.AITeamEmails_C.GetStringFromTeamPerformance
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentStanding                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SeasonTarget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  TeamPerformance                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::GetStringFromTeamPerformance(int32 CurrentStanding, int32 SeasonTarget, class UObject* __WorldContext, int32* TeamPerformance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "GetStringFromTeamPerformance");

	Params::AITeamEmails_C_GetStringFromTeamPerformance Parms{};

	Parms.CurrentStanding = CurrentStanding;
	Parms.SeasonTarget = SeasonTarget;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (TeamPerformance != nullptr)
		*TeamPerformance = Parms.TeamPerformance;
}


// Function AITeamEmails.AITeamEmails_C.GetTeamNameFromStandings
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FEmailFormulaData&         FormulaData                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FString*                          TeamName                                               (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
// int32*                                  CurrentPoints                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::GetTeamNameFromStandings(int32 position, const struct FEmailFormulaData& FormulaData, class UObject* __WorldContext, class FString* TeamName, int32* CurrentPoints)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "GetTeamNameFromStandings");

	Params::AITeamEmails_C_GetTeamNameFromStandings Parms{};

	Parms.position = position;
	Parms.FormulaData = std::move(FormulaData);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (TeamName != nullptr)
		*TeamName = std::move(Parms.TeamName);

	if (CurrentPoints != nullptr)
		*CurrentPoints = Parms.CurrentPoints;
}


// Function AITeamEmails.AITeamEmails_C.GetWinningDriverTeamID
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FEmailFormulaData&         EmailFormulaData                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  m_teamID                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::GetWinningDriverTeamID(const struct FEmailFormulaData& EmailFormulaData, class UObject* __WorldContext, int32* m_teamID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "GetWinningDriverTeamID");

	Params::AITeamEmails_C_GetWinningDriverTeamID Parms{};

	Parms.EmailFormulaData = std::move(EmailFormulaData);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (m_teamID != nullptr)
		*m_teamID = Parms.m_teamID;
}


// Function AITeamEmails.AITeamEmails_C.Monthly F1Report
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailData&                EmailData                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   Simdate                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::Monthly_F1Report(const struct FEmailData& EmailData, int32 Simdate, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "Monthly F1Report");

	Params::AITeamEmails_C_Monthly_F1Report Parms{};

	Parms.EmailData = std::move(EmailData);
	Parms.Simdate = Simdate;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function AITeamEmails.AITeamEmails_C.SpotlightTeamSection
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailTeamData&            EmailTeamData                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FNarrativeStaffMember&     TeamPrincipal                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FEmailSection*                   EmailSection                                           (Parm, OutParm)

void UAITeamEmails_C::SpotlightTeamSection(const struct FEmailTeamData& EmailTeamData, const struct FNarrativeStaffMember& TeamPrincipal, class UObject* __WorldContext, struct FEmailSection* EmailSection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "SpotlightTeamSection");

	Params::AITeamEmails_C_SpotlightTeamSection Parms{};

	Parms.EmailTeamData = std::move(EmailTeamData);
	Parms.TeamPrincipal = std::move(TeamPrincipal);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (EmailSection != nullptr)
		*EmailSection = std::move(Parms.EmailSection);
}


// Function AITeamEmails.AITeamEmails_C.TP1_AIPoaching
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailData&                Email_Data                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// int64                                   ReferenceID                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   SubReferenceID                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SimDay                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::TP1_AIPoaching(const struct FEmailData& Email_Data, int64 ReferenceID, int64 SubReferenceID, int32 SimDay, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "TP1_AIPoaching");

	Params::AITeamEmails_C_TP1_AIPoaching Parms{};

	Parms.Email_Data = std::move(Email_Data);
	Parms.ReferenceID = ReferenceID;
	Parms.SubReferenceID = SubReferenceID;
	Parms.SimDay = SimDay;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function AITeamEmails.AITeamEmails_C.TP2_ChampionshipCongratulations
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEmailData&                EmailData                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// int64                                   TeamPrincipalID                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   Points_Delta                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Simdate                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAITeamEmails_C::TP2_ChampionshipCongratulations(const struct FEmailData& EmailData, int64 TeamPrincipalID, int64 Points_Delta, int32 Simdate, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AITeamEmails_C", "TP2_ChampionshipCongratulations");

	Params::AITeamEmails_C_TP2_ChampionshipCongratulations Parms{};

	Parms.EmailData = std::move(EmailData);
	Parms.TeamPrincipalID = TeamPrincipalID;
	Parms.Points_Delta = Points_Delta;
	Parms.Simdate = Simdate;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
