#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AC_CircuitAmbience

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "RaceSim_structs.hpp"
#include "GameDatabase_structs.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AC_CircuitAmbience.BP_AC_CircuitAmbience_C
// 0x01A0 (0x0240 - 0x00A0)
class UBP_AC_CircuitAmbience_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioEmitterComponent*                 CircuitAmbience_Emitter;                           // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMap<class FString, class UAkAudioEvent*>     CircuitAmbience_TrackSelectorMap;                  // 0x00B0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 CurrentCircuitLevel;                               // 0x0100(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 CurrentLevelAfterReplace;                          // 0x0110(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UAkAudioEvent*                          Audio_CircuitAmbience_Stop;                        // 0x0120(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          Audio_CircuitAmbienceStart;                        // 0x0128(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bHasCameraModeChanged;                             // 0x0130(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	ECameraType                                   ECameraMode;                                       // 0x0131(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bIsAmbiencePlaying;                                // 0x0132(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_133[0x5];                                      // 0x0133(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_AC_RaceWeekend_GameStateManager_C*  RaceWeekendStateManager;                           // 0x0138(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMap<uint8, class FName>                      CameraMode_RaceStateMap;                           // 0x0140(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UBP_AC_AudioSceneManager_C*             Audio_Scene_Manager_Output;                        // 0x0190(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        GlobalRTPC_CrowdExcitement;                        // 0x0198(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CompletedLap;                                      // 0x01A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CrowdExcitementTimerHandle;                        // 0x01A8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          RedFlag_RaceRestart;                               // 0x01B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           Timer_OverrideCrowdExcitement;                     // 0x01B8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            CrowdExcitement;                                   // 0x01C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UMultiPointedEmitterComponent*          MediumDensity;                                     // 0x01C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMultiPointedEmitterComponent*          HighDensity;                                       // 0x01D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMultiPointedEmitterComponent*          PA_MultiPoint;                                     // 0x01D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            LapPercentage;                                     // 0x01E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMap<EWeekendFlowCinematicTag, class UAkAudioEvent*> WeekendFlowEventsMap;                       // 0x01E8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UAudioEmitterComponent*                 Helicam;                                           // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void Check_WeekendStage___Crowd_Excitement(EWeekendStage WeekendStage);
	class UMultiPointedEmitterComponent* CreateMultiDirectionsEmitter(class FName ComponentTag);
	class UMultiPointedEmitterComponent* CreateMultiSourcesEmitter(class FName ComponentTag);
	void CrowdReactions(const struct FRaceSimEvent& RaceSimEvent);
	void DoOnce_ResetCrowdExcitement();
	void ExecuteUbergraph_BP_AC_CircuitAmbience(int32 EntryPoint);
	void HomeDriver(uint8 carID, bool* Is_Home_Driver_);
	void InitialValues();
	void Overtake_Teammate(uint8 Car_ID, uint8 Other_Car_ID, bool* Is_not_Teammate_);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveTick(float DeltaSeconds);
	void RedFlag_ResetCrowdExcitement();
	void SetUpGrandstandEmitters();
	void SetupHelicamEmitter();
	void SetUpPAEmitter();
	void Update_Crowd_Excitement_RTPC();
	void Wait_for_Event_to_Finish(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AC_CircuitAmbience_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AC_CircuitAmbience_C")
	}
	static class UBP_AC_CircuitAmbience_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AC_CircuitAmbience_C>();
	}
};
DUMPER7_ASSERTS_UBP_AC_CircuitAmbience_C;

SDK_NAMESPACE_END
