#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AC_CameraBehaviour

#include "Basic.hpp"

#include "BP_AC_CameraBehaviour_classes.hpp"
#include "BP_AC_CameraBehaviour_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AC_CameraBehaviour.BP_AC_CameraBehaviour_C.ExecuteUbergraph_BP_AC_CameraBehaviour
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AC_CameraBehaviour_C::ExecuteUbergraph_BP_AC_CameraBehaviour(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AC_CameraBehaviour_C", "ExecuteUbergraph_BP_AC_CameraBehaviour");

	Params::BP_AC_CameraBehaviour_C_ExecuteUbergraph_BP_AC_CameraBehaviour Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AC_CameraBehaviour.BP_AC_CameraBehaviour_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_AC_CameraBehaviour_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AC_CameraBehaviour_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AC_CameraBehaviour.BP_AC_CameraBehaviour_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AC_CameraBehaviour_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AC_CameraBehaviour_C", "ReceiveTick");

	Params::BP_AC_CameraBehaviour_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
