#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DialogueBehaviour_Default

#include "Basic.hpp"

#include "Audio_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DialogueBehaviour_Default.BP_DialogueBehaviour_Default_C
// 0x0050 (0x0220 - 0x01D0)
class UBP_DialogueBehaviour_Default_C final : public UDialogueBehaviourBase
{
public:
	TMap<uint8, class FName>                      Default_Dialogue_Lines;                            // 0x01D0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void Play_VO(const class FString& DIalogue_ID);
	TArray<struct FPreparedDialogueLine> ProcessDialogueEvent(const struct FDialogueEvent& Event);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DialogueBehaviour_Default_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DialogueBehaviour_Default_C")
	}
	static class UBP_DialogueBehaviour_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DialogueBehaviour_Default_C>();
	}
};
DUMPER7_ASSERTS_UBP_DialogueBehaviour_Default_C;

SDK_NAMESPACE_END
