#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DialogueBehaviour_Default

#include "Basic.hpp"

#include "Audio_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_DialogueBehaviour_Default.BP_DialogueBehaviour_Default_C.Play VO
// 0x0010 (0x0010 - 0x0000)
struct BP_DialogueBehaviour_Default_C_Play_VO final
{
public:
	class FString                                 DIalogue_ID;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_DialogueBehaviour_Default_C_Play_VO;

// Function BP_DialogueBehaviour_Default.BP_DialogueBehaviour_Default_C.ProcessDialogueEvent
// 0x00E8 (0x00E8 - 0x0000)
struct BP_DialogueBehaviour_Default_C_ProcessDialogueEvent final
{
public:
	struct FDialogueEvent                         Event;                                             // 0x0000(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<struct FPreparedDialogueLine>          ReturnValue;                                       // 0x00D8(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_BP_DialogueBehaviour_Default_C_ProcessDialogueEvent;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
