#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DialogueBehaviour_Replays

#include "Basic.hpp"

#include "Audio_structs.hpp"
#include "Audio_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DialogueBehaviour_Replays.BP_DialogueBehaviour_Replays_C
// 0x0020 (0x01F0 - 0x01D0)
class UBP_DialogueBehaviour_Replays_C final : public UDialogueBehaviourBase
{
public:
	TArray<struct FPreparedDialogueLine>          OutputLines;                                       // 0x01D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        Reaction_Beat_Tuning_Delay_Min;                    // 0x01E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Reaction_Beat_Tuning_Delay_Max;                    // 0x01E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Adjust_incident_beat_timing(float Desired_Time, EDialogueSpeakerRole Role);
	void Process_Beat(const struct FDialogueBeat& Beat);
	TArray<struct FPreparedDialogueLine> ProcessDialogueEvent(const struct FDialogueEvent& Event);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DialogueBehaviour_Replays_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DialogueBehaviour_Replays_C")
	}
	static class UBP_DialogueBehaviour_Replays_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DialogueBehaviour_Replays_C>();
	}
};
DUMPER7_ASSERTS_UBP_DialogueBehaviour_Replays_C;

SDK_NAMESPACE_END
