#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DriverMenu_ModularCharacter

#include "Basic.hpp"

#include "RaceGame_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_DriverMenu_ModularCharacter.BP_DriverMenu_ModularCharacter_C.ExecuteUbergraph_BP_DriverMenu_ModularCharacter
// 0x0038 (0x0038 - 0x0000)
struct BP_DriverMenu_ModularCharacter_C_ExecuteUbergraph_BP_DriverMenu_ModularCharacter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStaffID                               CallFunc_GetLastAppliedStaffID_BP_ReturnValue;     // 0x0008(0x0010)(ConstParm, NoDestructor)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DoesDriverHaveHead_ReturnValue;           // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDriverMenu_Anim_BP_C*                  K2Node_DynamicCast_AsDriver_Menu_Anim_BP;          // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_DriverMenu_ModularCharacter_C_ExecuteUbergraph_BP_DriverMenu_ModularCharacter;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
