#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaceManagementGameMode

#include "Basic.hpp"

#include "BP_RaceManagementGameMode_classes.hpp"
#include "BP_RaceManagementGameMode_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_RaceManagementGameMode.BP_RaceManagementGameMode_C.ExecuteUbergraph_BP_RaceManagementGameMode
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceManagementGameMode_C::ExecuteUbergraph_BP_RaceManagementGameMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceManagementGameMode_C", "ExecuteUbergraph_BP_RaceManagementGameMode");

	Params::BP_RaceManagementGameMode_C_ExecuteUbergraph_BP_RaceManagementGameMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
