#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaceSimNotificationsManager

#include "Basic.hpp"

#include "BP_RaceSimNotificationsManager_classes.hpp"
#include "BP_RaceSimNotificationsManager_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_RaceSimNotificationsManager.BP_RaceSimNotificationsManager_C.ExecuteUbergraph_BP_RaceSimNotificationsManager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_RaceSimNotificationsManager_C::ExecuteUbergraph_BP_RaceSimNotificationsManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceSimNotificationsManager_C", "ExecuteUbergraph_BP_RaceSimNotificationsManager");

	Params::BP_RaceSimNotificationsManager_C_ExecuteUbergraph_BP_RaceSimNotificationsManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceSimNotificationsManager.BP_RaceSimNotificationsManager_C.RaceSimEventReceived
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRaceSimEvent&             i_event                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UBP_RaceSimNotificationsManager_C::RaceSimEventReceived(const struct FRaceSimEvent& i_event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceSimNotificationsManager_C", "RaceSimEventReceived");

	Params::BP_RaceSimNotificationsManager_C_RaceSimEventReceived Parms{};

	Parms.i_event = std::move(i_event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceSimNotificationsManager.BP_RaceSimNotificationsManager_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_RaceSimNotificationsManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceSimNotificationsManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceSimNotificationsManager.BP_RaceSimNotificationsManager_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_RaceSimNotificationsManager_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceSimNotificationsManager_C", "ReceiveTick");

	Params::BP_RaceSimNotificationsManager_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
