#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TM_SCSlow

#include "Basic.hpp"

#include "BP_TopicManagerBPBase_classes.hpp"
#include "ETopicType_structs.hpp"
#include "GameDatabase_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TM_SCSlow.BP_TM_SCSlow_C
// 0x0008 (0x0108 - 0x0100)
class UBP_TM_SCSlow_C final : public UBP_TopicManagerBPBase_C
{
public:
	uint8                                         Pad_F9[0x3];                                       // 0x00F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SCTime;                                            // 0x00FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsActive;                                          // 0x0100(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          TopicHasSet;                                       // 0x0101(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BeginPlay();
	void TopicPlayed();
	void Update(double Delta_Time);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TM_SCSlow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TM_SCSlow_C")
	}
	static class UBP_TM_SCSlow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TM_SCSlow_C>();
	}
};
DUMPER7_ASSERTS_UBP_TM_SCSlow_C;

SDK_NAMESPACE_END
