#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TM_TrackPosition

#include "Basic.hpp"

#include "RaceSim_structs.hpp"
#include "ETopicType_structs.hpp"
#include "BP_TopicManagerBPBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TM_TrackPosition.BP_TM_TrackPosition_C
// 0x0050 (0x0150 - 0x0100)
class UBP_TM_TrackPosition_C final : public UBP_TopicManagerBPBase_C
{
public:
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<ETopicType>                              AllTopics;                                         // 0x0100(0x0050)(Edit, BlueprintVisible)

public:
	void BeginPlay();
	void TopicPlayed();
	void Update(double Delta_Time);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TM_TrackPosition_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TM_TrackPosition_C")
	}
	static class UBP_TM_TrackPosition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TM_TrackPosition_C>();
	}
};
DUMPER7_ASSERTS_UBP_TM_TrackPosition_C;

SDK_NAMESPACE_END
