#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TM_TyreWearTopicsBase

#include "Basic.hpp"

#include "RaceSim_structs.hpp"
#include "ETopicType_structs.hpp"
#include "BP_TopicManagerBPBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TM_TyreWearTopicsBase.BP_TM_TyreWearTopicsBase_C
// 0x0000 (0x0100 - 0x0100)
class UBP_TM_TyreWearTopicsBase_C : public UBP_TopicManagerBPBase_C
{
public:
	ETeamCarIndex                                 PlayerCar;                                         // 0x00F9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopicType                                    ActiveTopic;                                       // 0x00FA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Reset_Bool;                                        // 0x00FB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BeginPlay();
	void TopicPlayed();
	void Update(double Delta_Time);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TM_TyreWearTopicsBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TM_TyreWearTopicsBase_C")
	}
	static class UBP_TM_TyreWearTopicsBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TM_TyreWearTopicsBase_C>();
	}
};
DUMPER7_ASSERTS_UBP_TM_TyreWearTopicsBase_C;

SDK_NAMESPACE_END
