#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TM_FlyingLapWarn

#include "Basic.hpp"

#include "BP_TopicManagerBPBase_classes.hpp"
#include "RaceSim_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TM_FlyingLapWarn.BP_TM_FlyingLapWarn_C
// 0x0000 (0x0100 - 0x0100)
class UBP_TM_FlyingLapWarn_C final : public UBP_TopicManagerBPBase_C
{
public:
	void BeginPlay();
	void TopicPlayed();
	void Update(double Delta_Time);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TM_FlyingLapWarn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TM_FlyingLapWarn_C")
	}
	static class UBP_TM_FlyingLapWarn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TM_FlyingLapWarn_C>();
	}
};
DUMPER7_ASSERTS_UBP_TM_FlyingLapWarn_C;

SDK_NAMESPACE_END
