#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TP_Traffic

#include "Basic.hpp"

#include "BP_TalkingPointBPBase_classes.hpp"
#include "RaceSim_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TP_Traffic.BP_TP_Traffic_C
// 0x0008 (0x0108 - 0x0100)
class UBP_TP_Traffic_C final : public UBP_TalkingPointBPBase_C
{
public:
	uint8                                         TR_OtherCar;                                       // 0x00F9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FA[0x6];                                       // 0x00FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_TM_Traffic_C*                       TopicObject;                                       // 0x0100(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BeginPlay();
	struct FCommsRequestBlueprintData CreateCommsRequest();
	void TalkingPointDisplayed();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TP_Traffic_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TP_Traffic_C")
	}
	static class UBP_TP_Traffic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TP_Traffic_C>();
	}
};
DUMPER7_ASSERTS_UBP_TP_Traffic_C;

SDK_NAMESPACE_END
