#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TP_CompetitorDRSLostBase

#include "Basic.hpp"

#include "RaceSim_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_TP_CompetitorDRSLostBase.BP_TP_CompetitorDRSLostBase_C.CreateCommsRequest
// 0x0078 (0x0078 - 0x0000)
struct BP_TP_CompetitorDRSLostBase_C_CreateCommsRequest final
{
public:
	struct FCommsRequestBlueprintData             ReturnValue;                                       // 0x0000(0x0020)(Parm, OutParm, ReturnParm)
	ECommsEventType                               NewLocalVar;                                       // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommsRequestBlueprintData             CallFunc_CreateCommsRequest_ReturnValue;           // 0x0028(0x0020)()
	class UAudioContextManager*                   CallFunc_GetAudioContextmanager_ReturnValue;       // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_AudioGetPlayerCar_ReturnValue;            // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommsRequestBlueprintData             K2Node_MakeStruct_CommsRequestBlueprintData;       // 0x0058(0x0020)()
};
DUMPER7_ASSERTS_BP_TP_CompetitorDRSLostBase_C_CreateCommsRequest;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
