#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ultra_Dynamic_Sky

#include "Basic.hpp"

#include "BP_Ultra_Dynamic_Sky_classes.hpp"
#include "BP_Ultra_Dynamic_Sky_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Apply Saved UDS and UDW State
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FUDS_and_UDW_State&        State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Apply_Saved_UDS_and_UDW_State(const struct FUDS_and_UDW_State& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Apply Saved UDS and UDW State");

	Params::BP_Ultra_Dynamic_Sky_C_Apply_Saved_UDS_and_UDW_State Parms{};

	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Approximate Real Sun Moon and Stars
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Month_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Day_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Year_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Time_of_Day_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Time_Zone_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Sun_Vector                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Moon_Vector                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 Real_Phase                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Phase_Alignment                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 Celestial_Orbit                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor*                    Celestial_Yaw                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Approximate_Real_Sun_Moon_and_Stars(int32 Month_0, int32 Day_0, int32 Year_0, double Time_of_Day_0, double Time_Zone_0, struct FVector* Sun_Vector, struct FVector* Moon_Vector, double* Real_Phase, struct FVector* Phase_Alignment, double* Celestial_Orbit, struct FLinearColor* Celestial_Yaw)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Approximate Real Sun Moon and Stars");

	Params::BP_Ultra_Dynamic_Sky_C_Approximate_Real_Sun_Moon_and_Stars Parms{};

	Parms.Month_0 = Month_0;
	Parms.Day_0 = Day_0;
	Parms.Year_0 = Year_0;
	Parms.Time_of_Day_0 = Time_of_Day_0;
	Parms.Time_Zone_0 = Time_Zone_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Sun_Vector != nullptr)
		*Sun_Vector = std::move(Parms.Sun_Vector);

	if (Moon_Vector != nullptr)
		*Moon_Vector = std::move(Parms.Moon_Vector);

	if (Real_Phase != nullptr)
		*Real_Phase = Parms.Real_Phase;

	if (Phase_Alignment != nullptr)
		*Phase_Alignment = std::move(Parms.Phase_Alignment);

	if (Celestial_Orbit != nullptr)
		*Celestial_Orbit = Parms.Celestial_Orbit;

	if (Celestial_Yaw != nullptr)
		*Celestial_Yaw = std::move(Parms.Celestial_Yaw);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.CallTimeOfDayChanged
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::CallTimeOfDayChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "CallTimeOfDayChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Change Settings Based on Platform and Scalability
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Change_Settings_Based_on_Platform_and_Scalability()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Change Settings Based on Platform and Scalability");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Check for Daylight Savings Time
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Check_for_Daylight_Savings_Time()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Check for Daylight Savings Time");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Construction Script Function
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Run_by_Counterpart                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Construction_Script_Function(bool Run_by_Counterpart)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Construction Script Function");

	Params::BP_Ultra_Dynamic_Sky_C_Construction_Script_Function Parms{};

	Parms.Run_by_Counterpart = Run_by_Counterpart;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Create UDS and UDW State for Saving
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FUDS_and_UDW_State*              Packaged_State                                         (Parm, OutParm, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Create_UDS_and_UDW_State_for_Saving(struct FUDS_and_UDW_State* Packaged_State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Create UDS and UDW State for Saving");

	Params::BP_Ultra_Dynamic_Sky_C_Create_UDS_and_UDW_State_for_Saving Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Packaged_State != nullptr)
		*Packaged_State = std::move(Parms.Packaged_State);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Day Ended
// (BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Day_Ended()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Day Ended");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.ExecuteUbergraph_BP_Ultra_Dynamic_Sky
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::ExecuteUbergraph_BP_Ultra_Dynamic_Sky(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "ExecuteUbergraph_BP_Ultra_Dynamic_Sky");

	Params::BP_Ultra_Dynamic_Sky_C_ExecuteUbergraph_BP_Ultra_Dynamic_Sky Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.FindTimeOfDayChangedActors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::FindTimeOfDayChangedActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "FindTimeOfDayChangedActors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Force Valid Day
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Force_Valid_Day()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Force Valid Day");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Get Current Date and Time
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDateTime*                       Current_Date_and_Time                                  (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Get_Current_Date_and_Time(struct FDateTime* Current_Date_and_Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Get Current Date and Time");

	Params::BP_Ultra_Dynamic_Sky_C_Get_Current_Date_and_Time Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Current_Date_and_Time != nullptr)
		*Current_Date_and_Time = std::move(Parms.Current_Date_and_Time);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Get Time of Day in Real Time Format
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTimecode*                       Time                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Get_Time_of_Day_in_Real_Time_Format(struct FTimecode* Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Get Time of Day in Real Time Format");

	Params::BP_Ultra_Dynamic_Sky_C_Get_Time_of_Day_in_Real_Time_Format Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Time != nullptr)
		*Time = std::move(Parms.Time);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Increment Day
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Increment_Day()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Increment Day");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.OnRep_Replicated Time of Day
// (BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::OnRep_Replicated_Time_of_Day()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "OnRep_Replicated Time of Day");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Recapture_SkyLight
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Recapture_SkyLight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Recapture_SkyLight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "ReceiveTick");

	Params::BP_Ultra_Dynamic_Sky_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Restart Inside Cloud Fog
// (BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Restart_Inside_Cloud_Fog()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Restart Inside Cloud Fog");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Set Cloud Timing
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Set_Cloud_Timing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Set Cloud Timing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Set Date and Time
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDateTime&                 Date_Time                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Set_Date_and_Time(const struct FDateTime& Date_Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Set Date and Time");

	Params::BP_Ultra_Dynamic_Sky_C_Set_Date_and_Time Parms{};

	Parms.Date_Time = std::move(Date_Time);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Set Height Fog Sky Lighting
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Fog_Density                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Set_Height_Fog_Sky_Lighting(double Fog_Density)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Set Height Fog Sky Lighting");

	Params::BP_Ultra_Dynamic_Sky_C_Set_Height_Fog_Sky_Lighting Parms{};

	Parms.Fog_Density = Fog_Density;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Set Sun and Moon Root Rotation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Set_Sun_and_Moon_Root_Rotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Set Sun and Moon Root Rotation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Set Time of Day using Time Code
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTimecode&                 Time_Code                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Set_Time_of_Day_using_Time_Code(const struct FTimecode& Time_Code)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Set Time of Day using Time Code");

	Params::BP_Ultra_Dynamic_Sky_C_Set_Time_of_Day_using_Time_Code Parms{};

	Parms.Time_Code = std::move(Time_Code);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.TimeOfDayChangedHandler
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TimeOfDay                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  SunElevation                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  CloudCoverage                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::TimeOfDayChangedHandler(double TimeOfDay, double SunElevation, double CloudCoverage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "TimeOfDayChangedHandler");

	Params::BP_Ultra_Dynamic_Sky_C_TimeOfDayChangedHandler Parms{};

	Parms.TimeOfDay = TimeOfDay;
	Parms.SunElevation = SunElevation;
	Parms.CloudCoverage = CloudCoverage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Active Variables
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Update_Active_Variables()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Active Variables");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Current Volumetric Clouds MID
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Update_Current_Volumetric_Clouds_MID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Current Volumetric Clouds MID");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Directional Lights
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Move_Static_Lights                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Update_Directional_Lights(bool Move_Static_Lights)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Directional Lights");

	Params::BP_Ultra_Dynamic_Sky_C_Update_Directional_Lights Parms{};

	Parms.Move_Static_Lights = Move_Static_Lights;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Inscattering Color Unless Overridden
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UExponentialHeightFogComponent*   self2                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ultra_Dynamic_Sky_C::Update_Inscattering_Color_Unless_Overridden(class UExponentialHeightFogComponent* self2, const struct FLinearColor& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Inscattering Color Unless Overridden");

	Params::BP_Ultra_Dynamic_Sky_C_Update_Inscattering_Color_Unless_Overridden Parms{};

	Parms.self2 = self2;
	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Lights
// (BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Update_Lights()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Lights");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Replicated Time
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Update_Replicated_Time()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Replicated Time");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Replicated ToD
// (BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Update_Replicated_ToD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Replicated ToD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Static Clouds
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Update_Static_Clouds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Static Clouds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Static Variables
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Update_Static_Variables()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Static Variables");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.Update Variables Controlled by Weather
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::Update_Variables_Controlled_by_Weather()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "Update Variables Controlled by Weather");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.UpdateTick
// (BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::UpdateTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "UpdateTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ultra_Dynamic_Sky.BP_Ultra_Dynamic_Sky_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Ultra_Dynamic_Sky_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ultra_Dynamic_Sky_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
