#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CutsceneCar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RaceSim_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CutsceneCar.CutsceneCar_C
// 0x0030 (0x0C20 - 0x0BF0)
class ACutsceneCar_C final : public ACutsceneCar
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BF0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_SteeringWheel_A_C*                  BP_SteeringWheel_A;                                // 0x0BF8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_CarMaterialController_C*            BP_CarMaterialController;                          // 0x0C00(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        Decal;                                             // 0x0C08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          DisableWheelRaycast;                               // 0x0C10(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          VisbileInEditor;                                   // 0x0C11(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BuildCar(bool* WaitForDayAdvanceCompletion);
	void Day_Advance_Complete();
	void DebugBuildCar();
	void ExecuteUbergraph_CutsceneCar(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CutsceneCar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CutsceneCar_C")
	}
	static class ACutsceneCar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACutsceneCar_C>();
	}
};
DUMPER7_ASSERTS_ACutsceneCar_C;

SDK_NAMESPACE_END
