#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Driver_ModularCharacter_BP

#include "Basic.hpp"

#include "Driver_ModularCharacter_BP_classes.hpp"
#include "Driver_ModularCharacter_BP_parameters.hpp"


SDK_NAMESPACE_START

// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.ExecuteUbergraph_Driver_ModularCharacter_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADriver_ModularCharacter_BP_C::ExecuteUbergraph_Driver_ModularCharacter_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "ExecuteUbergraph_Driver_ModularCharacter_BP");

	Params::Driver_ModularCharacter_BP_C_ExecuteUbergraph_Driver_ModularCharacter_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.GearChangeEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ChangeUp                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADriver_ModularCharacter_BP_C::GearChangeEvent(bool ChangeUp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "GearChangeEvent");

	Params::Driver_ModularCharacter_BP_C_GearChangeEvent Parms{};

	Parms.ChangeUp = ChangeUp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.OnActiveCameraChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class URaceSimCameraComponent*          NewCamera                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ADriver_ModularCharacter_BP_C::OnActiveCameraChanged(class URaceSimCameraComponent* NewCamera)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "OnActiveCameraChanged");

	Params::Driver_ModularCharacter_BP_C_OnActiveCameraChanged Parms{};

	Parms.NewCamera = NewCamera;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.OvertakeEvent
// (BlueprintCallable, BlueprintEvent)

void ADriver_ModularCharacter_BP_C::OvertakeEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "OvertakeEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.RadioEvent
// (BlueprintCallable, BlueprintEvent)

void ADriver_ModularCharacter_BP_C::RadioEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "RadioEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.RandomVisorTint
// (Public, BlueprintCallable, BlueprintEvent)

void ADriver_ModularCharacter_BP_C::RandomVisorTint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "RandomVisorTint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ADriver_ModularCharacter_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADriver_ModularCharacter_BP_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "ReceiveEndPlay");

	Params::Driver_ModularCharacter_BP_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Driver_ModularCharacter_BP.Driver_ModularCharacter_BP_C.Timer
// (BlueprintCallable, BlueprintEvent)

void ADriver_ModularCharacter_BP_C::Timer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Driver_ModularCharacter_BP_C", "Timer");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
