#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_TeamColours

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameDatabase_structs.hpp"
#include "F_TeamColourBlock_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct F_TeamColours.F_TeamColours
// 0x0150 (0x0150 - 0x0000)
struct FF_TeamColours final
{
public:
	EF1Team                                       TeamName_8_E6357C2240DEB0750AB14DB61F3C4E8D;       // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance*                      TeamFlag_15_1C5850CE4419D84D827992BBC7FC1127;      // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstance*                      TeamNationalFlag_36_F155C5C4499876CA883299B9D8E45B34; // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstance*                      thirdflag_19_5FD2432745BD14FCDD11D7B102B2B2B0;     // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                TeamFlag_Scale_28_AB698CEE409A068E96AB1AB3C38CC455; // 0x0020(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                TeamNationalFlagScale_34_72BB6EA347308A8B89B8FDA20856B238; // 0x0038(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                ThirdFlagScale_38_BBF28B294C8E80256D3306994A319C12; // 0x0050(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMesh*                            PitBannerLogo_56_06B7FEC24C18CE58ADAB328180458A67; // 0x0068(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             PitBannerLogoTransform_59_AE7602B148C923B8907272937C386B0E; // 0x0070(0x0060)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMesh*                            PitBoxMarking_62_D0FEF0DE4B094FB29C0C468F02FBA191; // 0x00D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D8[0x8];                                       // 0x00D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             PitGantryLogoTransform_68_353395A041E5228EEACE90A0FFA8FDD4; // 0x00E0(0x0060)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FF_TeamColourBlock>             TeamColours_86_2F1BDF574CD5335B4A6E97A91840E03C;   // 0x0140(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FF_TeamColours;

SDK_NAMESPACE_END
