#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FReverbCircuitDefinition

#include "Basic.hpp"

#include "EReverbCircuitTypes_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct FReverbCircuitDefinition.FReverbCircuitDefinition
// 0x000C (0x000C - 0x0000)
struct FFReverbCircuitDefinition final
{
public:
	class FName                                   CircuitName_2_FD471FED4F7CBFEA3BB1E3BC181DB2AD;    // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EReverbCircuitTypes                           ReverbType_5_EE583A01413368FDA101B4AABBFF2BA4;     // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FFReverbCircuitDefinition;

SDK_NAMESPACE_END
