#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenuFadeWidget

#include "Basic.hpp"

#include "MainMenuFadeWidget_classes.hpp"
#include "MainMenuFadeWidget_parameters.hpp"


SDK_NAMESPACE_START

// Function MainMenuFadeWidget.MainMenuFadeWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainMenuFadeWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuFadeWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuFadeWidget.MainMenuFadeWidget_C.ExecuteUbergraph_MainMenuFadeWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenuFadeWidget_C::ExecuteUbergraph_MainMenuFadeWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuFadeWidget_C", "ExecuteUbergraph_MainMenuFadeWidget");

	Params::MainMenuFadeWidget_C_ExecuteUbergraph_MainMenuFadeWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenuFadeWidget.MainMenuFadeWidget_C.Fade Out
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Speed_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenuFadeWidget_C::Fade_Out(double Speed_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuFadeWidget_C", "Fade Out");

	Params::MainMenuFadeWidget_C_Fade_Out Parms{};

	Parms.Speed_0 = Speed_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenuFadeWidget.MainMenuFadeWidget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenuFadeWidget_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuFadeWidget_C", "Tick");

	Params::MainMenuFadeWidget_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
