#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MovieWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "Audio_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass MovieWidget.MovieWidget_C
// 0x0058 (0x02D0 - 0x0278)
class UMovieWidget_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Background;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Video;                                             // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMediaPlayer*                           MediaPlayer;                                       // 0x0290(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UBaseMediaSource*                       MediaSource;                                       // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsTitleSequence;                                   // 0x02A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A1[0x7];                                      // 0x02A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 AudioEvent_StartMusic;                             // 0x02A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UAkAudioEvent*                          Audio_Event_Start_Music_Ref;                       // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           Audio_TitleMovieTimer;                             // 0x02C0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCatIntro;                                        // 0x02C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Audio_Begin_Music();
	void Construct();
	void ExecuteUbergraph_MovieWidget(int32 EntryPoint);
	void On_End_Reached();
	void On_Media_Opened(const class FString& OpenedUrl);
	void On_Media_Opened_Failed(const class FString& FailedUrl);
	void On_Skip_Cinematic();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MovieWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MovieWidget_C")
	}
	static class UMovieWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMovieWidget_C>();
	}
};
DUMPER7_ASSERTS_UMovieWidget_C;

SDK_NAMESPACE_END
