#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MultiUserClientLibrary

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// Enum MultiUserClientLibrary.EMultiUserConnectionError
// NumValues: 0x000B
enum class EMultiUserConnectionError : uint32
{
	None                                     = 0,
	Canceled                                 = 1,
	ConnectionAttemptAborted                 = 2,
	ServerNotResponding                      = 3,
	ServerError                              = 4,
	WorkspaceValidationUnknown               = 100,
	SourceControlValidationUnknown           = 110,
	SourceControlValidationCanceled          = 111,
	SourceControlValidationError             = 112,
	DirtyPackageValidationError              = 113,
	EMultiUserConnectionError_MAX            = 114,
};

// Enum MultiUserClientLibrary.EMultiUserSourceValidationMode
// NumValues: 0x0004
enum class EMultiUserSourceValidationMode : uint8
{
	Hard                                     = 0,
	Soft                                     = 1,
	SoftAutoProceed                          = 2,
	EMultiUserSourceValidationMode_MAX       = 3,
};

// Enum MultiUserClientLibrary.EMultiUserConnectionStatus
// NumValues: 0x0005
enum class EMultiUserConnectionStatus : uint8
{
	Connecting                               = 0,
	Connected                                = 1,
	Disconnecting                            = 2,
	Disconnected                             = 3,
	EMultiUserConnectionStatus_MAX           = 4,
};

// ScriptStruct MultiUserClientLibrary.MultiUserClientInfo
// 0x0040 (0x0040 - 0x0000)
struct FMultiUserClientInfo final
{
public:
	struct FGuid                                  ClientEndpointId;                                  // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DisplayName;                                       // 0x0010(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           AvatarColor;                                       // 0x0020(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           Tags;                                              // 0x0030(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, AdvancedDisplay, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMultiUserClientInfo;

// ScriptStruct MultiUserClientLibrary.MultiUserConnectionError
// 0x0020 (0x0020 - 0x0000)
struct FMultiUserConnectionError final
{
public:
	EMultiUserConnectionError                     ErrorCode;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   ErrorMessage;                                      // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMultiUserConnectionError;

// ScriptStruct MultiUserClientLibrary.MultiUserClientConfig
// 0x0038 (0x0038 - 0x0000)
struct FMultiUserClientConfig final
{
public:
	class FString                                 DefaultServerURL;                                  // 0x0000(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DefaultSessionName;                                // 0x0010(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DefaultSessionToRestore;                           // 0x0020(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMultiUserSourceValidationMode                ValidationMode;                                    // 0x0030(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FMultiUserClientConfig;

SDK_NAMESPACE_END
