#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OnboardingStepStruct

#include "Basic.hpp"

#include "GameDatabase_structs.hpp"
#include "Audio_structs.hpp"
#include "RaceGame_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct OnboardingStepStruct.OnboardingStepStruct
// 0x0050 (0x0050 - 0x0000)
struct FOnboardingStepStruct final
{
public:
	EOnboardingTutorialSequence                   Sequence_16_CB8D2C4C4CB22FFB73488C9CFB6364E3;      // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 StepName_10_8007D04C45BB09EF32CD469F0D27ACE8;      // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	EOnboardingNextStepType                       NextStepType_18_3F349FBC46D52DCC462D84B370250AF2;  // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 NextStepValue_20_E850798D4BEDA0B8D9F8B0868FBCE47F; // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 NextStepValue_2_22_8C4EF7124DDF15BDBEEC9BBB3822E79E; // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	EOnboardingTrigger                            DialogueTrigger_24_F66446E34EBF8BD0739B79B8AA166B59; // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        VO_PreDelay_8_33A1EF33464B18A98CFF388A5E4C5FD6;    // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FOnboardingStepStruct;

SDK_NAMESPACE_END
