#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PostExternalSource

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PostExternalSource.PostExternalSource_C
// 0x0000 (0x0028 - 0x0028)
class UPostExternalSource_C final : public UBlueprintFunctionLibrary
{
public:
	static void PostExternalVO(class AActor* Actor, class UAkExternalMediaAsset* External_Source_Asset, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PostExternalSource_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PostExternalSource_C")
	}
	static class UPostExternalSource_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPostExternalSource_C>();
	}
};
DUMPER7_ASSERTS_UPostExternalSource_C;

SDK_NAMESPACE_END
