#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RaceSimChroma

#include "Basic.hpp"

#include "RaceSimChroma_classes.hpp"
#include "RaceSimChroma_parameters.hpp"


SDK_NAMESPACE_START

// Function RaceSimChroma.RaceSimChroma_C.ExecuteUbergraph_RaceSimChroma
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URaceSimChroma_C::ExecuteUbergraph_RaceSimChroma(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "ExecuteUbergraph_RaceSimChroma");

	Params::RaceSimChroma_C_ExecuteUbergraph_RaceSimChroma Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RaceSimChroma.RaceSimChroma_C.OnSwooshStart
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ETransitionManagerAnimType              AnimType_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URaceSimChroma_C::OnSwooshStart(ETransitionManagerAnimType AnimType_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "OnSwooshStart");

	Params::RaceSimChroma_C_OnSwooshStart Parms{};

	Parms.AnimType_0 = AnimType_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RaceSimChroma.RaceSimChroma_C.OnSwooshStop
// (BlueprintCallable, BlueprintEvent)

void URaceSimChroma_C::OnSwooshStop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "OnSwooshStop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaceSimChroma.RaceSimChroma_C.PlayCqFlagAnims
// (Public, BlueprintCallable, BlueprintEvent)

void URaceSimChroma_C::PlayCqFlagAnims()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "PlayCqFlagAnims");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaceSimChroma.RaceSimChroma_C.PlayRedFlagAnims
// (Public, BlueprintCallable, BlueprintEvent)

void URaceSimChroma_C::PlayRedFlagAnims()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "PlayRedFlagAnims");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaceSimChroma.RaceSimChroma_C.PlaySwooshAnims
// (Public, BlueprintCallable, BlueprintEvent)

void URaceSimChroma_C::PlaySwooshAnims()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "PlaySwooshAnims");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaceSimChroma.RaceSimChroma_C.PlayYellowFlagAnims
// (Public, BlueprintCallable, BlueprintEvent)

void URaceSimChroma_C::PlayYellowFlagAnims()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "PlayYellowFlagAnims");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaceSimChroma.RaceSimChroma_C.RaceSimEventRecieved
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRaceSimEvent&             i_event                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void URaceSimChroma_C::RaceSimEventRecieved(const struct FRaceSimEvent& i_event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "RaceSimEventRecieved");

	Params::RaceSimChroma_C_RaceSimEventRecieved Parms{};

	Parms.i_event = std::move(i_event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function RaceSimChroma.RaceSimChroma_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void URaceSimChroma_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaceSimChroma.RaceSimChroma_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URaceSimChroma_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaceSimChroma_C", "ReceiveTick");

	Params::RaceSimChroma_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
