#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RaceManagement

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameDatabase_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// Enum RaceManagement.EAIResponseCurveShape
// NumValues: 0x000B
enum class EAIResponseCurveShape : uint8
{
	Linear                                   = 0,
	Polynomial                               = 1,
	Logistic                                 = 2,
	Logit                                    = 3,
	Normal                                   = 4,
	SineWave                                 = 5,
	Constant                                 = 6,
	Step                                     = 7,
	Custom                                   = 8,
	Preset                                   = 9,
	EAIResponseCurveShape_MAX                = 10,
};

// Enum RaceManagement.EAICurvePresetInputChangeType
// NumValues: 0x0008
enum class EAICurvePresetInputChangeType : uint8
{
	None                                     = 0,
	GraduallyMoreAppealing                   = 1,
	GraduallyLessAppealing                   = 2,
	Constant                                 = 3,
	Fluctuating                              = 4,
	DiscreteStepMoreAppealing                = 5,
	DiscreteStepLessAppealing                = 6,
	EAICurvePresetInputChangeType_MAX        = 7,
};

// Enum RaceManagement.EAICurvePresetOutputChangeRate
// NumValues: 0x0009
enum class EAICurvePresetOutputChangeRate : uint8
{
	None                                     = 0,
	Linear                                   = 1,
	FirstSlowThenFast                        = 2,
	FirstFastThenSlow                        = 3,
	Dynamic                                  = 4,
	SlowOnEndsFastInMiddle                   = 5,
	FastOnEndsSlowInMiddle                   = 6,
	DiscreteThreshold                        = 7,
	EAICurvePresetOutputChangeRate_MAX       = 8,
};

// Enum RaceManagement.EAIAction
// NumValues: 0x0010
enum class EAIAction : uint8
{
	INVALID                                  = 0,
	ProposeContract                          = 1,
	UpgradeBuilding                          = 2,
	RefurbishBuilding                        = 3,
	DesignCarPart                            = 4,
	ResearchCarPart                          = 5,
	ManufactureCarPart                       = 6,
	ReplaceCarPart                           = 7,
	SelectSpendingStrategy                   = 8,
	ReconcileBudget                          = 9,
	SelectSponsorPackages                    = 10,
	CastRegulationVote                       = 11,
	FIRST                                    = 1,
	LAST                                     = 11,
	COUNT                                    = 12,
	EAIAction_MAX                            = 13,
};

// Enum RaceManagement.EAIConfigurableTask
// NumValues: 0x000A
enum class EAIConfigurableTask : uint8
{
	RankStaffCandidates                      = 0,
	SelectMaxContractLength                  = 1,
	SelectContractBreakoutClause             = 2,
	SelectContractGenerosity                 = 3,
	SelectIdealPartsAmount                   = 4,
	SelectPartsManufactureAmount             = 5,
	RankSponsorPackagePaymentPlan            = 6,
	RankSpendingStrategyPreset               = 7,
	RankProposedRegulationChange             = 8,
	EAIConfigurableTask_MAX                  = 9,
};

// Enum RaceManagement.EAIActionTargetType
// NumValues: 0x0006
enum class EAIActionTargetType : uint8
{
	None                                     = 0,
	StaffMember                              = 1,
	Facility                                 = 2,
	PartType                                 = 3,
	CarLoadout                               = 4,
	EAIActionTargetType_MAX                  = 5,
};

// Enum RaceManagement.EAITargetEvaluationFunctionType
// NumValues: 0x0004
enum class EAITargetEvaluationFunctionType : uint8
{
	NONE                                     = 0,
	Overriding                               = 1,
	Additive                                 = 2,
	EAITargetEvaluationFunctionType_MAX      = 3,
};

// Enum RaceManagement.EAIInputParamType
// NumValues: 0x0006
enum class EAIInputParamType : uint8
{
	Boolean                                  = 0,
	ValueRange                               = 1,
	EnumValue                                = 2,
	EnumStatValue                            = 3,
	BooleanLogic                             = 4,
	EAIInputParamType_MAX                    = 5,
};

// Enum RaceManagement.EAILogicOperator
// NumValues: 0x0005
enum class EAILogicOperator : uint8
{
	ALL                                      = 0,
	NONE                                     = 1,
	ANY                                      = 2,
	OnlyOne                                  = 3,
	EAILogicOperator_MAX                     = 4,
};

// Enum RaceManagement.EDriverState
// NumValues: 0x0006
enum class EDriverState : uint8
{
	INVALID                                  = 0,
	WantsChampionDriverNumber                = 1,
	HasWonF2                                 = 2,
	HasWonF3                                 = 3,
	HasSuperLicense                          = 4,
	EDriverState_MAX                         = 5,
};

// Enum RaceManagement.EDriverData
// NumValues: 0x0008
enum class EDriverData : uint8
{
	INVALID                                  = 0,
	Improvability                            = 1,
	Aggression                               = 2,
	CurrentMarketability                     = 3,
	TargetMarketability                      = 4,
	MarketabilityProgress                    = 5,
	TotalCareerF1Points                      = 6,
	EDriverData_MAX                          = 7,
};

// Enum RaceManagement.EStaffCommonData
// NumValues: 0x0009
enum class EStaffCommonData : uint8
{
	INVALID                                  = 0,
	Mentality                                = 1,
	PerformanceRating                        = 2,
	ExperiencePoints                         = 3,
	Patience                                 = 4,
	TeamOpinionRating                        = 5,
	TeamSuitabilityRating                    = 6,
	TeamOpinionDeltaToStaffTeam              = 7,
	EStaffCommonData_MAX                     = 8,
};

// Enum RaceManagement.EPlayerStaffPoachingRecords
// NumValues: 0x0007
enum class EPlayerStaffPoachingRecords : uint8
{
	INVALID                                  = 0,
	TotalAttempts                            = 1,
	TotalSuccesfulPoachings                  = 2,
	RemainingAttempts                        = 3,
	RemainingSuccessfulPoachings             = 4,
	MinimumAttemptsDelta                     = 5,
	EPlayerStaffPoachingRecords_MAX          = 6,
};

// Enum RaceManagement.EPartInventoryDataType
// NumValues: 0x0006
enum class EPartInventoryDataType : uint8
{
	INVALID                                  = 0,
	InWarehouse                              = 1,
	InManufacturing                          = 2,
	InstalledOnCar                           = 3,
	TotalItemCount                           = 4,
	EPartInventoryDataType_MAX               = 5,
};

// Enum RaceManagement.EBoardExpectationStat
// NumValues: 0x000B
enum class EBoardExpectationStat : uint8
{
	INVALID                                  = 0,
	StaffQualityScore                        = 1,
	DriverQualityScore                       = 2,
	AffiliateDriverScore                     = 3,
	HQQualityScore                           = 4,
	CarQualityScore                          = 5,
	AverageQualityScore                      = 6,
	TeamRating                               = 7,
	TeamRatingRank                           = 8,
	ChampionshipPoints                       = 9,
	EBoardExpectationStat_MAX                = 10,
};

// Enum RaceManagement.EAIActionCategory
// NumValues: 0x000B
enum class EAIActionCategory : uint8
{
	NONE                                     = 0,
	StaffManagement                          = 1,
	Facilities                               = 2,
	CarDevelopment                           = 3,
	Finances                                 = 4,
	SeasonEvents                             = 5,
	Miscellaneous                            = 6,
	TeamManagement                           = 7,
	RegulationVoting                         = 8,
	COUNT                                    = 9,
	EAIActionCategory_MAX                    = 10,
};

// Enum RaceManagement.EAIDecisionEvaluationTrigger
// NumValues: 0x0006
enum class EAIDecisionEvaluationTrigger : uint8
{
	CalendarDateRange                        = 0,
	Monthly                                  = 1,
	SeasonDeadlines                          = 2,
	Weekly                                   = 3,
	Daily                                    = 4,
	EAIDecisionEvaluationTrigger_MAX         = 5,
};

// Enum RaceManagement.EAIActionResult
// NumValues: 0x0005
enum class EAIActionResult : uint8
{
	Failed                                   = 0,
	Success                                  = 1,
	Aborted                                  = 2,
	CannotExecute                            = 3,
	EAIActionResult_MAX                      = 4,
};

// Enum RaceManagement.EStaffEmploymentStatus
// NumValues: 0x0008
enum class EStaffEmploymentStatus : uint8
{
	FreeAgent                                = 0,
	F1MainDriver                             = 1,
	F1AffiliateDriver                        = 2,
	F1Staff                                  = 3,
	NonF1Driver                              = 4,
	NonF1Staff                               = 5,
	INVALID                                  = 6,
	EStaffEmploymentStatus_MAX               = 7,
};

// ScriptStruct RaceManagement.AIActionMetadata
// 0x0050 (0x0058 - 0x0008)
struct FAIActionMetadata final : public FTableRowBase
{
public:
	EAIAction                                     ActionType;                                        // 0x0008(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAIActionTargetType                           TargetType;                                        // 0x0009(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAIActionCategory                             Category;                                          // 0x000A(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B[0x5];                                        // 0x000B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UAIDecisionData>            PayloadType;                                       // 0x0010(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         Targets;                                           // 0x0018(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, NativeAccessSpecifierPublic)
	bool                                          bShowTasks;                                        // 0x0028(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EAIConfigurableTask>                   Tasks;                                             // 0x0030(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	class FString                                 Description;                                       // 0x0040(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bValidAction;                                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAIActionMetadata;

// ScriptStruct RaceManagement.AIConsiderationMetadata
// 0x0098 (0x00A0 - 0x0008)
struct FAIConsiderationMetadata final : public FTableRowBase
{
public:
	bool                                          bImplementedInCode;                                // 0x0008(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAIInputParamType                             InputType;                                         // 0x0009(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UAIConsiderationData>       DataType;                                          // 0x0010(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        ValidCategories;                                   // 0x0018(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              ValidInputRange;                                   // 0x0020(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EnumPackage;                                       // 0x0030(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRoundToInt;                                       // 0x0040(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bValidEnumClass;                                   // 0x0041(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         EnumOptions;                                       // 0x0048(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, NativeAccessSpecifierPublic)
	bool                                          bAcceptsPayload;                                   // 0x0058(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PayloadEnumPackage;                                // 0x0060(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bValidPayloadEnumClass;                            // 0x0070(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         PayloadEnumOptions;                                // 0x0078(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, EditConst, NativeAccessSpecifierPublic)
	class FString                                 Description;                                       // 0x0088(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   RowName;                                           // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FAIConsiderationMetadata;

// ScriptStruct RaceManagement.AIConsideration
// 0x0028 (0x0028 - 0x0000)
struct FAIConsideration final
{
public:
	class FName                                   Type;                                              // 0x0000(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Description;                                       // 0x0008(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAIConsiderationData*                   InputParams;                                       // 0x0018(0x0008)(Edit, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoClear, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        Category;                                          // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAIConsideration;

// ScriptStruct RaceManagement.AIDecisionContext
// 0x0760 (0x0760 - 0x0000)
struct FAIDecisionContext final
{
public:
	class UDatabaseManager*                       m_databaseManager;                                 // 0x0000(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAITargetData*                          m_targetData;                                      // 0x0008(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EAIAction                                     m_actionType;                                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_11[0x74F];                                     // 0x0011(0x074F)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAIDecisionContext;

// ScriptStruct RaceManagement.AIResponseCurvePresetSettings
// 0x0002 (0x0002 - 0x0000)
struct FAIResponseCurvePresetSettings final
{
public:
	EAICurvePresetInputChangeType                 ChangeType;                                        // 0x0000(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAICurvePresetOutputChangeRate                ChangeRate;                                        // 0x0001(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAIResponseCurvePresetSettings;

// ScriptStruct RaceManagement.AIResponseCurveParams
// 0x0020 (0x0020 - 0x0000)
struct FAIResponseCurveParams final
{
public:
	float                                         Slope;                                             // 0x0000(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LogBase;                                           // 0x0004(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Exponent;                                          // 0x0008(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         XShift;                                            // 0x000C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         YShift;                                            // 0x0010(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Steps;                                             // 0x0014(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StepBaseY;                                         // 0x0018(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         NumCurveKeys;                                      // 0x001C(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERichCurveInterpMode                          DefaultKeyInterpMode;                              // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERichCurveTangentMode                         DefaultKeyTangentMode;                             // 0x001E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERichCurveTangentWeightMode                   DefaultKeyTangentWeightMode;                       // 0x001F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAIResponseCurveParams;

// ScriptStruct RaceManagement.AIResponseCurvePreset
// 0x00B0 (0x00B8 - 0x0008)
struct FAIResponseCurvePreset final : public FTableRowBase
{
public:
	struct FAIResponseCurvePresetSettings         Settings;                                          // 0x0008(0x0002)(Edit, DisableEditOnInstance, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAIResponseCurveParams                 Params;                                            // 0x000C(0x0020)(Edit, DisableEditOnInstance, NoDestructor, Protected, NativeAccessSpecifierProtected)
	EAIResponseCurveShape                         Shape;                                             // 0x002C(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRuntimeFloatCurve                     Curve;                                             // 0x0030(0x0088)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
};
DUMPER7_ASSERTS_FAIResponseCurvePreset;

// ScriptStruct RaceManagement.LevelData
// 0x0008 (0x0008 - 0x0000)
struct FLevelData final
{
public:
	class ULevelStreaming*                        m_subLevel;                                        // 0x0000(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FLevelData;

// ScriptStruct RaceManagement.ACineCameraActorArray
// 0x0010 (0x0010 - 0x0000)
struct FACineCameraActorArray final
{
public:
	TArray<class ACineCameraActor*>               actorArray;                                        // 0x0000(0x0010)(ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FACineCameraActorArray;

// ScriptStruct RaceManagement.ManagementData
// 0x000C (0x000C - 0x0000)
struct FManagementData final
{
public:
	ERaceTrack                                    NextRaceTrack;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         NextRaceDay;                                       // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CurrentDay;                                        // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FManagementData;

SDK_NAMESPACE_END
