#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SponsorEmailFunctionLibrary

#include "Basic.hpp"

#include "RaceGame_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "RaceGameCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SponsorEmailFunctionLibrary.SponsorEmailFunctionLibrary_C.SponsorPackageConfirmed
// 0x0C20 (0x0C20 - 0x0000)
struct SponsorEmailFunctionLibrary_C_SponsorPackageConfirmed final
{
public:
	struct FEmailData                             EmailData;                                         // 0x0000(0x0990)(BlueprintVisible, BlueprintReadOnly, Parm)
	int32                                         SimDay;                                            // 0x0990(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_994[0x4];                                      // 0x0994(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0998(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FEmailAttachment>               SponsorshipPackageAttachment_0;                    // 0x09A0(0x0010)(Edit, BlueprintVisible)
	struct FNarrativeStaffMember                  CallFunc_Get_Email_Narrative_Staff_Member_Narrative_Staff_Member; // 0x09B0(0x0058)()
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0A08(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A0C[0x4];                                      // 0x0A0C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDateTime                              CallFunc_ConvertNumberToDate_ReturnValue;          // 0x0A10(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_AppendGender_ReturnValue;                 // 0x0A18(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Year;                       // 0x0A28(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Month;                      // 0x0A2C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Day;                        // 0x0A30(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Hour;                       // 0x0A34(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Minute;                     // 0x0A38(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Second;                     // 0x0A3C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Millisecond;                // 0x0A40(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A44[0x4];                                      // 0x0A44(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLocStringParameter                    K2Node_MakeStruct_LocStringParameter;              // 0x0A48(0x0028)()
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0A70(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FLocStringParameter                    K2Node_MakeStruct_LocStringParameter_1;            // 0x0A80(0x0028)()
	struct FLocStringParameter                    K2Node_MakeStruct_LocStringParameter_2;            // 0x0AA8(0x0028)()
	struct FLocStringParameter                    K2Node_MakeStruct_LocStringParameter_3;            // 0x0AD0(0x0028)()
	int32                                         CallFunc_ConvertDateToNumber_ReturnValue;          // 0x0AF8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AFC[0x4];                                      // 0x0AFC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FLocStringParameter>            K2Node_MakeArray_Array;                            // 0x0B00(0x0010)(ConstParm, ReferenceParm)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0B10(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B11[0x7];                                      // 0x0B11(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_BuildLocalisationString_ReturnValue;      // 0x0B18(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_Int64Int64_ReturnValue;        // 0x0B28(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_Int64Int64_ReturnValue_1;      // 0x0B29(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0B2A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2B[0x5];                                      // 0x0B2B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FEmailAttachment>               CallFunc_SponsorshipPackageAttachment_Attachment;  // 0x0B30(0x0010)(ReferenceParm)
	TArray<struct FEmailLink>                     Temp_struct_Variable;                              // 0x0B40(0x0010)(ConstParm, ReferenceParm)
	struct FLocStringParameter                    K2Node_MakeStruct_LocStringParameter_4;            // 0x0B50(0x0028)()
	TArray<struct FEmailDilemmaResponse>          Temp_struct_Variable_1;                            // 0x0B78(0x0010)(ConstParm, ReferenceParm)
	TArray<struct FLocStringParameter>            K2Node_MakeArray_Array_1;                          // 0x0B88(0x0010)(ConstParm, ReferenceParm)
	struct FEmailChainInfo                        Temp_struct_Variable_2;                            // 0x0B98(0x0018)(ConstParm, NoDestructor)
	class FString                                 CallFunc_BuildLocalisationString_ReturnValue_1;    // 0x0BB0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_SelectString_ReturnValue;                 // 0x0BC0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FEmailSection                          K2Node_MakeStruct_EmailSection;                    // 0x0BD0(0x0040)()
	TArray<struct FEmailSection>                  K2Node_MakeArray_Array_2;                          // 0x0C10(0x0010)(ConstParm, ReferenceParm)
};
DUMPER7_ASSERTS_SponsorEmailFunctionLibrary_C_SponsorPackageConfirmed;

// Function SponsorEmailFunctionLibrary.SponsorEmailFunctionLibrary_C.SponsorshipPackageAttachment
// 0x0698 (0x0698 - 0x0000)
struct SponsorEmailFunctionLibrary_C_SponsorshipPackageAttachment final
{
public:
	struct FEmailSponsorshipData                  EmailSponsorshipData;                              // 0x0000(0x0060)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          Create_A_Team;                                     // 0x0060(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0068(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FEmailAttachment>               Attachment;                                        // 0x0070(0x0010)(ConstParm, Parm, OutParm)
	int32                                         AdditionalRaceDayPay;                              // 0x0080(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         AdditionalEngagementPay;                           // 0x0084(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         AdditionalUpfrontPay;                              // 0x0088(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEmailAdditionalSponsorsData           CallFunc_Array_Get_Item;                           // 0x0090(0x0028)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEmailAttachmentStatValue              K2Node_MakeStruct_EmailAttachmentStatValue;        // 0x00C8(0x0008)(NoDestructor)
	struct FEmailAttachmentStatValue              K2Node_MakeStruct_EmailAttachmentStatValue_1;      // 0x00D0(0x0008)(NoDestructor)
	TArray<struct FEmailAttachmentStatValue>      K2Node_MakeArray_Array;                            // 0x00D8(0x0010)(ReferenceParm)
	TArray<struct FEmailAttachmentStatValue>      K2Node_MakeArray_Array_1;                          // 0x00E8(0x0010)(ReferenceParm)
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat;             // 0x00F8(0x0058)()
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_1;           // 0x0150(0x0058)()
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_2;            // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_3;            // 0x01AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEmailAttachmentStatValue              K2Node_MakeStruct_EmailAttachmentStatValue_2;      // 0x01B0(0x0008)(NoDestructor)
	struct FEmailAttachmentStatValue              K2Node_MakeStruct_EmailAttachmentStatValue_3;      // 0x01B8(0x0008)(NoDestructor)
	TArray<struct FEmailAttachmentStatValue>      K2Node_MakeArray_Array_2;                          // 0x01C0(0x0010)(ReferenceParm)
	TArray<struct FEmailAttachmentStatValue>      K2Node_MakeArray_Array_3;                          // 0x01D0(0x0010)(ReferenceParm)
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_2;           // 0x01E0(0x0058)()
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_3;           // 0x0238(0x0058)()
	TArray<class FString>                         K2Node_MakeArray_Array_4;                          // 0x0290(0x0010)(ReferenceParm)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x02A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A4[0x4];                                      // 0x02A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_4;           // 0x02A8(0x0058)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0300(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_301[0x3];                                      // 0x0301(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0304(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0308(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x030C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_311[0x3];                                      // 0x0311(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0314(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_4;            // 0x0318(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_5;            // 0x031C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEmailAttachmentStatValue              K2Node_MakeStruct_EmailAttachmentStatValue_4;      // 0x0320(0x0008)(NoDestructor)
	struct FEmailAttachmentStatValue              K2Node_MakeStruct_EmailAttachmentStatValue_5;      // 0x0328(0x0008)(NoDestructor)
	TArray<struct FEmailAttachmentStatValue>      K2Node_MakeArray_Array_5;                          // 0x0330(0x0010)(ReferenceParm)
	TArray<struct FEmailAttachmentStatValue>      K2Node_MakeArray_Array_6;                          // 0x0340(0x0010)(ReferenceParm)
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_5;           // 0x0350(0x0058)()
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_6;           // 0x03A8(0x0058)()
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_7;           // 0x0400(0x0058)()
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_6;            // 0x0458(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45C[0x4];                                      // 0x045C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_8;           // 0x0460(0x0058)()
	struct FEmailAttachmentStatValue              K2Node_MakeStruct_EmailAttachmentStatValue_6;      // 0x04B8(0x0008)(NoDestructor)
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_9;           // 0x04C0(0x0058)()
	TArray<struct FEmailAttachmentStatValue>      K2Node_MakeArray_Array_7;                          // 0x0518(0x0010)(ReferenceParm)
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_10;          // 0x0528(0x0058)()
	struct FEmailAttachmentStat                   K2Node_MakeStruct_EmailAttachmentStat_11;          // 0x0580(0x0058)()
	TArray<struct FEmailAttachmentStat>           K2Node_MakeArray_Array_8;                          // 0x05D8(0x0010)(ReferenceParm)
	TArray<struct FEmailAttachmentStat>           K2Node_MakeArray_Array_9;                          // 0x05E8(0x0010)(ReferenceParm)
	struct FEmailAttachment                       K2Node_MakeStruct_EmailAttachment;                 // 0x05F8(0x0020)()
	struct FEmailAttachment                       K2Node_MakeStruct_EmailAttachment_1;               // 0x0618(0x0020)()
	TArray<struct FEmailAttachmentStat>           K2Node_MakeArray_Array_10;                         // 0x0638(0x0010)(ReferenceParm)
	struct FEmailAttachment                       K2Node_MakeStruct_EmailAttachment_2;               // 0x0648(0x0020)()
	struct FEmailAttachment                       K2Node_Select_Default;                             // 0x0668(0x0020)()
	TArray<struct FEmailAttachment>               K2Node_MakeArray_Array_11;                         // 0x0688(0x0010)(ConstParm, ReferenceParm)
};
DUMPER7_ASSERTS_SponsorEmailFunctionLibrary_C_SponsorshipPackageAttachment;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
