#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TestCarActor

#include "Basic.hpp"

#include "RaceSim_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass TestCarActor.TestCarActor_C
// 0x0030 (0x0B90 - 0x0B60)
class ATestCarActor_C final : public ACarActor
{
public:
	uint8                                         Pad_B58[0x8];                                      // 0x0B58(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_SteeringWheel_A_C*                  BP_SteeringWheel_A;                                // 0x0B60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_VFX_Car_DamageEvents_C*             BP_VFX_Car_DamageEvents;                           // 0x0B68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_VFX_Car_ContinuousFX_C*             BP_VFX_Car_ContinuousFX;                           // 0x0B70(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_CarMaterialController_C*            BP_CarMaterialController;                          // 0x0B78(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Driver;                                            // 0x0B80(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TestCarActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TestCarActor_C")
	}
	static class ATestCarActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATestCarActor_C>();
	}
};
DUMPER7_ASSERTS_ATestCarActor_C;

SDK_NAMESPACE_END
